name: Generate contribution snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: meomato
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push snake to output branch
        run: |
          cd dist
          git init
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b output
          git add github-contribution-grid-snake.svg
          git commit -m "Generate contribution snake"
          git push -f "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
